spring:
  application:
    name: rest-with-spring-boot-and-java
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_with_spring_boot?useTimeZone=true&serverTimeZone=UTF
    username: root
    password: 12345
  jpa:
    hibernate:
      #ddl-auto: update
      ddl-auto: none
    properties:
      hibernate:
        #dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false
    open-in-view: false
    #spring.jpa.open-in-view=false
  flyway:
    enabled: true
    locations: classpath:db/migration
logging:
  level:
      #org.flywaydb: DEBUG
      root: WARN
      #br.com.lucas: DEBUG